[2025-05-05 18:07:40,748] 20 root - INFO - \U0001f680 Starting Eye Disease Detection Pipeline Execution
[2025-05-05 18:07:40,749] 28 root - INFO - \U0001f4e5 Initiating Data Ingestion
[2025-05-05 18:08:51,486] 32 root - INFO - Copied input data to feature store at Artifacts\05_05_2025_18_07_39\data_ingestion\feature_store
[2025-05-05 18:10:05,478] 67 root - INFO - Train and Test split completed.
[2025-05-05 18:10:05,478] 81 root - INFO - Data Ingestion process completed.
[2025-05-05 18:10:05,478] 34 root - INFO - \u2705 Initiating Data Validation
[2025-05-05 18:10:05,479] 81 root - INFO - Starting Data Validation Process...
[2025-05-05 18:10:05,485] 75 root - INFO - Drift report saved at Artifacts\05_05_2025_18_07_39\data_validation\drift_report\report.yaml
[2025-05-05 18:10:05,487] 40 root - INFO - \U0001f501 Initiating Data Transformation
[2025-05-05 18:10:05,487] 52 root - INFO - Entered initiate_data_transformation method
[2025-05-05 18:10:05,487] 54 root - INFO - \U0001f501 Starting Data Transformation
[2025-05-05 18:10:05,487] 74 root - INFO - \U0001f5bc\ufe0f Transforming and saving training images...
[2025-05-05 18:11:20,878] 77 root - INFO - \U0001f5bc\ufe0f Transforming and saving validation images...
[2025-05-05 18:17:51,453] 87 root - INFO - \u2705 Data Transformation completed successfully.
[2025-05-05 18:17:51,453] 46 root - INFO - \U0001f9e0 Initiating Model Training
[2025-05-05 18:17:57,890] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB78D636D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:18:06,839] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB78F4EA10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:18:19,390] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB78F4CF40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:18:40,148] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB78F4DB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:19:16,444] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB78F4E200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:20:24,809] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB78F4DF00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:22:28,922] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB78F4DFF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
